apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-go-test 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    argocd/app-name: new-go-test
    janus-idp.io/tekton: new-go-test 
    backstage.io/kubernetes-id: new-go-test
    backstage.io/kubernetes-namespace: target-ns
    backstage.io/techdocs-ref: dir:. 
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 